In [1]:
import numpy as np
import pandas as pd
import os
import re
#os.getcwd()

In [2]:
data=pd.read_csv("SMSSpamCollection.csv",delimiter="\t") #Reading data
data.columns=['Type','Text'] #Changing Column names 
type(data) #Type is a data frame
data.head(5) #Displays first five records

Type                                               Text
0   ham                      Ok lar... Joking wif u oni...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  U dun say so early hor... U c already then say...
3   ham  Nah I don't think he goes to usf, he lives aro...
4  spam  FreeMsg Hey there darling it's been 3 week's n...

In [3]:
Text_data = data['Text']
#print(Text_data)


In [4]:
Text_data1 = Text_data.tolist()
#Some text preprocessing- Removing extra spaces and numbers
for i in range(len(Text_data1)):
    Text_data1[i]=re.sub(r'\s+', ' ', Text_data1[i]) #Removing white spaces in the sentence
    Text_data1[i]=re.sub('[\d]', '',Text_data1[i]) #Removing numbers




check out below links to know more about Regular expressions:

https://en.wikipedia.org/wiki/Regular_expression

https://docs.python.org/3/library/re.html

In [5]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
#count=CountVectorizer(strip_accents='unicode',ngram_range=(1,1),stop_words='english')
#tfreq=count.fit_transform(Text_data1)
#Dense_mat=tfreq.todense()
#A=pd.DataFrame(Dense_mat,columns=count.get_feature_names())

In [6]:
#Lets consider TF-idf
tfidf_transformer = TfidfVectorizer(ngram_range=(1,1),stop_words='english')
X_train_tfidf = tfidf_transformer.fit_transform(Text_data1)
X_train_tfidf.shape
Dense_mat=X_train_tfidf.todense()
A=pd.DataFrame(Dense_mat,columns=tfidf_transformer.get_feature_names())

A.shape

(5571, 7551)

In [27]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, data['Type'])
pred=clf.predict(X_train_tfidf)
print (data["Type"].value_counts())
from sklearn.metrics import confusion_matrix
prediction=confusion_matrix(data['Type'],pred)

ham     4824
spam     747
Name: Type, dtype: int64


In [29]:
#Metrics
from sklearn.metrics import recall_score, precision_score, accuracy_score
acc=accuracy_score(data['Type'],pred)
rec=recall_score(data['Type'],pred,pos_label='spam')
prec=precision_score(data['Type'],pred,pos_label='spam')


In [44]:
print ("accuracy= ", str(acc))
print ("recall= ",str(rec))
#print ("precision= ",str(prec))
print ("precision= ",str(prec))
print (confusion_matrix(data['Type'],pred))

accuracy=  0.9816908993
recall=  0.863453815261
precision=  1.0
[[4824    0]
 [ 102  645]]


In [46]:
#Logistic regression in sklearn
from sklearn import linear_model
logreg = linear_model.LogisticRegression()
clf_lr=logreg.fit(X_train_tfidf, data['Type'])
pred_lr=clf_lr.predict(X_train_tfidf)
print (pred_lr)
rec_lr=recall_score(data['Type'],pred_lr,pos_label='spam')

['ham' 'spam' 'ham' ..., 'ham' 'ham' 'ham']


#Perform the train test split on the data and then build the model

In [47]:
from sklearn.cross_validation import train_test_split

In [48]:
X_train, X_test, y_train, y_test=train_test_split(Dense_mat,data['Type'],test_size=0.3,random_state=1234)

In [49]:
X_train.shape

(3899, 7551)

In [50]:
X_train

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [51]:
X_test.shape

(1672, 7551)

In [52]:
y_train

5436     ham
3049     ham
1292     ham
2657     ham
3221    spam
2593     ham
1760     ham
1045     ham
2197     ham
768      ham
726      ham
698      ham
2660     ham
646      ham
4673     ham
2571     ham
618      ham
4214     ham
3242     ham
1477     ham
98       ham
5219     ham
79       ham
839     spam
5097    spam
643      ham
374     spam
3604     ham
4238     ham
3484     ham
        ... 
1282     ham
3        ham
2384     ham
3915     ham
4841     ham
2791     ham
5315     ham
1530     ham
4006     ham
5196     ham
3824     ham
3503     ham
2558     ham
246      ham
2431     ham
969      ham
3408    spam
3397     ham
2168     ham
2490     ham
5494     ham
1182     ham
30       ham
1257     ham
279      ham
664      ham
3276     ham
1318     ham
723      ham
2863     ham
Name: Type, Length: 3899, dtype: object

In [53]:
y_train.value_counts()

ham     3378
spam     521
Name: Type, dtype: int64

In [54]:
y_test.value_counts()

ham     1446
spam     226
Name: Type, dtype: int64

In [55]:
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
logreg_train = linear_model.LogisticRegression()
clf_lr=logreg_train.fit(X_train, y_train)
pred_lr_test=clf_lr.predict(X_test)
pred_lr_train=clf_lr.predict(X_train)
rec_lr_train=recall_score(y_train,pred_lr_train,pos_label='spam')
rec_lr_test=recall_score(y_test,pred_lr_test,pos_label='spam')

print (confusion_matrix(y_train,pred_lr_train))
print (confusion_matrix(y_test,pred_lr_test))

[[3374    4]
 [ 127  394]]
[[1443    3]
 [  83  143]]


In [56]:
from sklearn.naive_bayes import MultinomialNB
clf_train = MultinomialNB().fit(X_train, y_train)
pred=clf_train.predict(X_test)
prediction=confusion_matrix(y_test,pred)

In [57]:
prediction

array([[1446,    0],
       [  57,  169]], dtype=int64)